### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by huyttdn** [nabarvn/ai-image-generator#1]
npm install
npm run dev
and i see this error
![Capture](https://github.com/nabarvn/ai-image-generator/assets/35677570/349f0f4d-8e96-497b-aba2-8314819def18)

**Comment by nabarvn** [comment]
Hello there, you're seeing this error because `data` is undefined in your code as you haven't set up an Azure Function App yet. Please refer to <a href="https://github.com/nabarvn/dall-e-function-app"><strong>this repository</strong></a> or <a href="https://www.youtube.com/watch?v=0qHnVYSxZ4k&t=3893s"><strong>this video tutorial</strong></a> for further guidance.
